api_platform:
    title: Gestion_Backlog
    version: 1.0.0
    description: |
        Gestion_Backlog
    formats:
        json: ['application/json']
        html: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header